import type { Metadata } from 'next'
import { Inria_Sans } from 'next/font/google'
import './globals.css'

const inter = Inria_Sans({ subsets: ['latin'], weight: '400' })

export const metadata: Metadata = {
  title: '7vibez',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
